configfile: "config/config.yaml"

include: "rules/fastp.smk"
include: "rules/fastqc.smk"
include: "rules/alignment.smk"

samples = config["samples"]

rule all:
    input:
        expand("results/fastp/{sample}_fastp.html", sample=samples),
        expand("results/fastqc/{sample}_{stage}_fastqc.html",
               sample=samples, stage=["raw", "filtered"]),
        expand("results/alignment/{sample}.bam", sample=samples),
        expand("results/alignment/{sample}.bam.bai", sample=samples)
